"""
Gmail API wrapper — send + thread-history polling for reply detection.

Requires one-time OAuth setup (see README): a Google Cloud OAuth client
(Desktop app) + a refresh token generated by a human consent flow. Stored as
repo secrets: GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN,
GMAIL_SENDER (the address replies land in and sends come from).
"""

import base64
import os
from email.mime.text import MIMEText

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SCOPES = ["https://www.googleapis.com/auth/gmail.modify"]

_service = None


def get_service():
    global _service
    if _service is None:
        creds = Credentials(
            token=None,
            refresh_token=os.environ["GMAIL_REFRESH_TOKEN"],
            client_id=os.environ["GMAIL_CLIENT_ID"],
            client_secret=os.environ["GMAIL_CLIENT_SECRET"],
            token_uri="https://oauth2.googleapis.com/token",
            scopes=SCOPES,
        )
        _service = build("gmail", "v1", credentials=creds)
    return _service


def send_email(to: str, subject: str, body_text: str) -> dict:
    """Sends a new email (new thread). Returns {'message_id', 'thread_id'}."""
    sender = os.environ["GMAIL_SENDER"]
    message = MIMEText(body_text)
    message["to"] = to
    message["from"] = sender
    message["subject"] = subject
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    result = get_service().users().messages().send(userId="me", body={"raw": raw}).execute()
    return {"message_id": result["id"], "thread_id": result["threadId"]}


def send_followup(to: str, subject: str, body_text: str, thread_id: str) -> dict:
    """Sends a reply within an existing thread (day-3 nudge)."""
    sender = os.environ["GMAIL_SENDER"]
    message = MIMEText(body_text)
    message["to"] = to
    message["from"] = sender
    message["subject"] = subject if subject.lower().startswith("re:") else f"Re: {subject}"
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    result = get_service().users().messages().send(
        userId="me", body={"raw": raw, "threadId": thread_id}
    ).execute()
    return {"message_id": result["id"], "thread_id": result["threadId"]}


def get_latest_reply(thread_id: str, our_message_id: str) -> dict | None:
    """Returns the most recent message in the thread that ISN'T one we sent,
    or None if there's been no reply yet."""
    sender = os.environ["GMAIL_SENDER"]
    thread = get_service().users().threads().get(userId="me", id=thread_id, format="full").execute()
    messages = thread.get("messages", [])

    for msg in reversed(messages):  # newest first
        if msg["id"] == our_message_id:
            continue
        headers = {h["name"].lower(): h["value"] for h in msg["payload"].get("headers", [])}
        from_header = headers.get("from", "")
        if sender.lower() in from_header.lower():
            continue  # a follow-up we sent, not a reply

        return {"message_id": msg["id"], "body": _extract_body(msg["payload"]), "from": from_header}

    return None


def _extract_body(payload: dict) -> str:
    if payload.get("body", {}).get("data"):
        return base64.urlsafe_b64decode(payload["body"]["data"]).decode("utf-8", errors="replace")

    for part in payload.get("parts", []):
        if part.get("mimeType") == "text/plain" and part.get("body", {}).get("data"):
            return base64.urlsafe_b64decode(part["body"]["data"]).decode("utf-8", errors="replace")

    for part in payload.get("parts", []):
        text = _extract_body(part)
        if text:
            return text

    return ""
