"""
Gmail API wrapper — send + thread-history polling for reply detection.

Requires one-time OAuth setup (see README): a Google Cloud OAuth client
(Desktop app) + a refresh token generated by a human consent flow. Stored as
repo secrets: GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN.

The From address is NOT taken from a separately-configured secret — it's
read straight from the OAuth-authenticated account itself via
users.getProfile(). A mismatched From header (claiming to be an address
that isn't the one actually authenticated) is exactly what makes Gmail
recipients see "this message isn't authenticated" — SPF/DKIM get signed
against the real sending account, but DMARC alignment fails if the From:
header claims a different identity. Deriving it from the profile instead of
a hand-typed env var removes that whole class of mistake.
"""

import base64
import os
from email.mime.text import MIMEText

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

SCOPES = ["https://www.googleapis.com/auth/gmail.modify"]

_service = None
_sender_address: str | None = None


def get_service():
    global _service
    if _service is None:
        creds = Credentials(
            token=None,
            refresh_token=os.environ["GMAIL_REFRESH_TOKEN"],
            client_id=os.environ["GMAIL_CLIENT_ID"],
            client_secret=os.environ["GMAIL_CLIENT_SECRET"],
            token_uri="https://oauth2.googleapis.com/token",
            scopes=SCOPES,
        )
        _service = build("gmail", "v1", credentials=creds)
    return _service


def get_sender_address() -> str:
    """The actual authenticated mailbox address — always use this for the
    From header, never a separately-configured value that could drift out
    of sync with what the refresh token really authenticates as."""
    global _sender_address
    if _sender_address is None:
        profile = get_service().users().getProfile(userId="me").execute()
        _sender_address = profile["emailAddress"]
    return _sender_address


def send_email(to: str, subject: str, body_text: str) -> dict:
    """Sends a new email (new thread). Returns {'message_id', 'thread_id'}."""
    message = MIMEText(body_text)
    message["to"] = to
    message["from"] = get_sender_address()
    message["subject"] = subject
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    result = get_service().users().messages().send(userId="me", body={"raw": raw}).execute()
    return {"message_id": result["id"], "thread_id": result["threadId"]}


def create_draft(to: str, subject: str, body_text: str) -> dict:
    """Creates a draft in the authenticated account's own Drafts folder
    instead of sending — a human reviews and hits send themselves from
    within Gmail. Returns {'draft_id', 'message_id', 'thread_id'}."""
    message = MIMEText(body_text)
    message["to"] = to
    message["from"] = get_sender_address()
    message["subject"] = subject
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    result = get_service().users().drafts().create(
        userId="me", body={"message": {"raw": raw}}
    ).execute()
    return {
        "draft_id": result["id"],
        "message_id": result["message"]["id"],
        "thread_id": result["message"]["threadId"],
    }


def get_sent_message_in_thread(thread_id: str) -> dict | None:
    """Call this later to detect whether a human has actually hit send on a
    draft created by create_draft(). Returns {'message_id', 'internal_date'}
    for the first message in the thread carrying Gmail's SENT label once
    one exists, else None — still sitting as an unsent draft, or the draft
    was deleted without ever being sent (thread/draft gone entirely, 404)."""
    try:
        thread = get_service().users().threads().get(
            userId="me", id=thread_id, format="metadata"
        ).execute()
    except HttpError as e:
        if e.resp.status == 404:
            return None
        raise

    for msg in thread.get("messages", []):
        if "SENT" in msg.get("labelIds", []):
            return {"message_id": msg["id"], "internal_date": msg.get("internalDate")}

    return None


def send_followup(to: str, subject: str, body_text: str, thread_id: str) -> dict:
    """Sends a reply within an existing thread (day-3 nudge)."""
    message = MIMEText(body_text)
    message["to"] = to
    message["from"] = get_sender_address()
    message["subject"] = subject if subject.lower().startswith("re:") else f"Re: {subject}"
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    result = get_service().users().messages().send(
        userId="me", body={"raw": raw, "threadId": thread_id}
    ).execute()
    return {"message_id": result["id"], "thread_id": result["threadId"]}


def get_latest_reply(thread_id: str, our_message_id: str) -> dict | None:
    """Returns the most recent message in the thread that ISN'T one we sent,
    or None if there's been no reply yet."""
    sender = get_sender_address()
    thread = get_service().users().threads().get(userId="me", id=thread_id, format="full").execute()
    messages = thread.get("messages", [])

    for msg in reversed(messages):  # newest first
        if msg["id"] == our_message_id:
            continue
        headers = {h["name"].lower(): h["value"] for h in msg["payload"].get("headers", [])}
        from_header = headers.get("from", "")
        if sender.lower() in from_header.lower():
            continue  # a follow-up we sent, not a reply

        return {"message_id": msg["id"], "body": _extract_body(msg["payload"]), "from": from_header}

    return None


def _extract_body(payload: dict) -> str:
    if payload.get("body", {}).get("data"):
        return base64.urlsafe_b64decode(payload["body"]["data"]).decode("utf-8", errors="replace")

    for part in payload.get("parts", []):
        if part.get("mimeType") == "text/plain" and part.get("body", {}).get("data"):
            return base64.urlsafe_b64decode(part["body"]["data"]).decode("utf-8", errors="replace")

    for part in payload.get("parts", []):
        text = _extract_body(part)
        if text:
            return text

    return ""
